name: blindds_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.11.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  validators: ^3.0.0
  http: ^1.5.0
  logger: ^2.6.2
  provider: ^6.1.5+1
  google_sign_in: ^7.2.0
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

  # √çcones e Splash
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

  # Drift (Database)
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.0

  path: ^1.9.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.0

# ---------------------------------------------------------
# SPLASH SCREEN (corrigido)
# ---------------------------------------------------------
flutter_native_splash:
  color: "#04244A"
  image: "assets/public/images/Logo-2.png"
  android: true
  ios: true

# ---------------------------------------------------------
# LAUNCHER ICONS (corrigido)
# ---------------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/public/images/Logo-1.png"
  android_adaptive_icon_foreground: "assets/public/images/Logo-2.png"
  android_adaptive_icon_background: "#04244A"
  min_sdk_android: 21

# ---------------------------------------------------------
# FLUTTER CONFIG
# ---------------------------------------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/public/images/
    - .env

  fonts:
    - family: AtkinsonHyperlegible
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible/AtkinsonHyperlegible-Regular.ttf
        - asset: assets/fonts/AtkinsonHyperlegible/AtkinsonHyperlegible-Bold.ttf
          weight: 700
        - asset: assets/fonts/AtkinsonHyperlegible/AtkinsonHyperlegible-Italic.ttf
          style: italic
        - asset: assets/fonts/AtkinsonHyperlegible/AtkinsonHyperlegible-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf
          weight: 100
